services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: matilda
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 3062
      MYSQL_ROOT_PASSWORD: 3062
    ports:
      - "3309:3306"
    volumes:
      - ./matilda-data:/var/lib/mysql

  matilda-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    container_name: "matilda-prometheus"

  matilda-grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: "matilda-grafana"
    depends_on:
      - matilda-prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  redis:
    image: redis:7-alpine
    container_name: matilda-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass 3062

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis://matilda-redis:6379
      - REDIS_PASSWORD=3062  # ⚠️ Redis 비밀번호와 일치해야 함
    ports:
      - "9121:9121"          # Exporter 포트
    depends_on:
      - redis

volumes:
  grafana-data:
  prometheus-data:
  redis-data:
