global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9999' ]
    scrape_interval: 5s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: [ 'host.docker.internal:9121' ]
